"""Time helpers shared across Social Worker.

All timestamps produced here are timezone-aware UTC values so that reports
generated by workers in different geographic test locations remain comparable.
"""

from __future__ import annotations

import random
from datetime import datetime, timedelta, timezone
from typing import Final

UTC: Final = timezone.utc


def utc_now() -> datetime:
    """Return the current time as a timezone-aware UTC datetime."""
    return datetime.now(UTC)


def iso(moment: datetime | None = None) -> str:
    """Render *moment* (default: now) as an ISO-8601 string."""
    return (moment or utc_now()).isoformat()


def timestamp_slug(moment: datetime | None = None) -> str:
    """Filesystem-safe timestamp, e.g. ``20260817-141233-482``."""
    moment = moment or utc_now()
    return moment.strftime("%Y%m%d-%H%M%S-") + f"{moment.microsecond // 1000:03d}"


def date_slug(moment: datetime | None = None) -> str:
    """Return ``YYYY-MM-DD`` for *moment* (default: now)."""
    return (moment or utc_now()).strftime("%Y-%m-%d")


def minutes(value: float) -> float:
    """Convert minutes to seconds."""
    return value * 60.0


def jitter(seconds: float, ratio: float = 0.1) -> float:
    """Apply a small +/- *ratio* jitter to *seconds*.

    Used only to make authorized load profiles look like organic traffic for
    capacity-planning purposes -- never as an evasion mechanism.
    """
    if seconds <= 0:
        return 0.0
    spread = seconds * max(0.0, ratio)
    return max(0.0, random.uniform(seconds - spread, seconds + spread))


def random_interval(minimum: float, maximum: float) -> float:
    """Return a uniform random value between *minimum* and *maximum*."""
    if maximum < minimum:
        minimum, maximum = maximum, minimum
    return random.uniform(minimum, maximum)


def duration_ms(start: datetime, end: datetime | None = None) -> float:
    """Return the elapsed milliseconds between *start* and *end* (default now)."""
    return ((end or utc_now()) - start).total_seconds() * 1000.0


def humanize(seconds: float) -> str:
    """Render a duration in a compact ``1h 02m 03s`` form."""
    if seconds < 0:
        seconds = 0
    delta = timedelta(seconds=int(seconds))
    hours, remainder = divmod(int(delta.total_seconds()), 3600)
    mins, secs = divmod(remainder, 60)
    if hours:
        return f"{hours}h {mins:02d}m {secs:02d}s"
    if mins:
        return f"{mins}m {secs:02d}s"
    return f"{secs}s"


def parse_hhmm(value: str) -> tuple[int, int]:
    """Parse an ``HH:MM`` string into an (hour, minute) tuple."""
    parts = value.strip().split(":")
    if len(parts) != 2:
        raise ValueError(f"Expected HH:MM, got {value!r}")
    hour, minute = int(parts[0]), int(parts[1])
    if not (0 <= hour <= 23 and 0 <= minute <= 59):
        raise ValueError(f"Time out of range: {value!r}")
    return hour, minute


def within_window(moment: datetime, start: str, end: str) -> bool:
    """Return True when *moment* falls inside the ``HH:MM`` window [start, end).

    Windows that wrap past midnight (e.g. ``22:00``-``04:00``) are supported.
    """
    start_h, start_m = parse_hhmm(start)
    end_h, end_m = parse_hhmm(end)
    now_minutes = moment.hour * 60 + moment.minute
    start_minutes = start_h * 60 + start_m
    end_minutes = end_h * 60 + end_m
    if start_minutes == end_minutes:
        return True
    if start_minutes < end_minutes:
        return start_minutes <= now_minutes < end_minutes
    return now_minutes >= start_minutes or now_minutes < end_minutes
